application: subway-franchise
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on 

handlers:
- url: /fonts
  static_dir: static/fonts

- url: /images
  static_dir: static/images

- url: /scripts
  static_dir: static/scripts

- url: /stylesheets
  static_dir: static/stylesheets

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest